### ISSUE TITLE
Валится тест

### ISSUE THREAD

**Issue by rptl8sr** [DimaKropachev/calc-service#1]
<img width="1588" alt="image" src="https://github.com/user-attachments/assets/3ff3e425-7f64-4dac-a77d-bdc7d00837a1" />

остальное норм

**Comment by DimaKropachev** [comment]
Исправил. Теперь должно всё работать. Спасибо, что указали на ошибку)

**Comment by rptl8sr** [comment]
Ага, ща работает :)
